Import libraries

In [1]:
import random
import pandas as pd

from datetime import datetime, timedelta

In [2]:
priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

categories = [
    "Core HR",
    "Benefits",
    "Payroll",
    "Time Management",
    "Recruitment",
    "Performance"
]

channels = [
    "Email",
    "Phone",
    "Chat",
    "Portal"
]

statuses = [
    "Open",
    "In Progress",
    "Resolved",
    "Closed"
]

regions = [
    "North America",
    "Europe",
    "Asia Pacific",
    "Latin America"
]

Define subcategories

In [3]:
sub_categories = {
    "Core HR": [
        "Employee Profile",
        "Job Information",
        "Personal Information",
        "Employment Status"
    ],

    "Benefits": [
        "Health Insurance",
        "Life Insurance",
        "Retirement",
        "Benefit Enrollment"
    ],

    "Payroll": [
        "Pay Statement",
        "Direct Deposit",
        "Tax",
        "Overtime"
    ],

    "Time Management": [
        "Time Entry",
        "Leave",
        "Attendance",
        "Overtime"
    ],

    "Recruitment": [
        "Candidate Profile",
        "Job Posting",
        "Interview",
        "Offer"
    ],

    "Performance": [
        "Performance Review",
        "Goals",
        "Feedback",
        "Rating"
    ]
}

Define issue descriptions

In [4]:
issue_descriptions = [
    "Employee is unable to update their profile",
    "Employee cannot access the benefit enrollment page",
    "Employee is unable to view their pay statement",
    "Direct deposit information is not updating",
    "Employee cannot submit their time entry",
    "Employee is unable to request leave",
    "Candidate information is not displaying correctly",
    "Manager cannot complete the performance review",
    "Employee is unable to update personal information",
    "Employee cannot access the application"
]

Define possible resolutions

In [5]:
resolutions = [
    "Configuration was updated",
    "User permissions were corrected",
    "Data was corrected in the system",
    "Employee was provided with the required instructions",
    "Issue was resolved after configuration update",
    "System behavior was verified and corrected",
    "Knowledge article was provided",
    "Issue was escalated to the appropriate team"
]

Define the date range

In [11]:
start_date = datetime(2025, 1, 1)

end_date = datetime(2026, 9, 1)

In [12]:
def generate_random_date():

    days_difference = (
        end_date - start_date
    ).days

    random_days = random.randint(
        0,
        days_difference
    )

    random_date = (
        start_date
        + timedelta(days=random_days)
    )

    return random_date

Generate a closed date

In [13]:
def generate_closed_date(created_date):

    resolution_days = random.randint(
        0,
        10
    )

    closed_date = (
        created_date
        + timedelta(days=resolution_days)
    )

    return closed_date

Generate ONE ticket

In [14]:
def generate_ticket(ticket_number):

    category = random.choice(categories)

    created_date = generate_random_date()

    closed_date = generate_closed_date(
        created_date
    )

    ticket = {
        "ticket_id": f"TKT{ticket_number:07d}",

        "customer_id":
            f"CUST{random.randint(1, 50000):05d}",

        "agent_id":
            f"AG{random.randint(1, 1000):04d}",

        "created_date":
            created_date,

        "closed_date":
            closed_date,

        "priority":
            random.choice(priorities),

        "category":
            category,

        "sub_category":
            random.choice(
                sub_categories[category]
            ),

        "product":
            "HCM",

        "status":
            random.choice(statuses),

        "channel":
            random.choice(channels),

        "issue_description":
            random.choice(issue_descriptions),

        "resolution":
            random.choice(resolutions),

        "customer_region":
            random.choice(regions),

        "first_response_minutes":
            random.randint(5, 600),

        "resolution_hours":
            round(
                random.uniform(1, 200),
                2
            ),

        "customer_satisfaction":
            random.randint(1, 5),

        "escalation_flag":
            random.choice(["Yes", "No"])
    }

    return ticket

Test ONE ticket

In [15]:
ticket = generate_ticket(1)

print(ticket)

{'ticket_id': 'TKT0000001', 'customer_id': 'CUST06628', 'agent_id': 'AG0463', 'created_date': datetime.datetime(2025, 8, 13, 0, 0), 'closed_date': datetime.datetime(2025, 8, 18, 0, 0), 'priority': 'Low', 'category': 'Performance', 'sub_category': 'Goals', 'product': 'HCM', 'status': 'Closed', 'channel': 'Chat', 'issue_description': 'Manager cannot complete the performance review', 'resolution': 'Employee was provided with the required instructions', 'customer_region': 'Latin America', 'first_response_minutes': 132, 'resolution_hours': 163.84, 'customer_satisfaction': 1, 'escalation_flag': 'Yes'}

Generate 10 tickets

In [16]:
records = []

for ticket_number in range(1, 11):

    ticket = generate_ticket(
        ticket_number
    )

    records.append(ticket)

In [17]:
test_df = pd.DataFrame(records)
test_df

,ticket_id,customer_id,agent_id,created_date,closed_date,priority,category,sub_category,product,status,channel,issue_description,resolution,customer_region,first_response_minutes,resolution_hours,customer_satisfaction,escalation_flag
0,TKT0000001,CUST05532,AG0389,2025-11-04,2025-11-12,Low,Payroll,Pay Statement,HCM,Open,Phone,Candidate information is not displaying correctly,Issue was resolved after configuration update,Europe,451,125.03,5,Yes
1,TKT0000002,CUST34709,AG0633,2025-08-19,2025-08-28,Medium,Benefits,Retirement,HCM,Open,Portal,Employee is unable to view their pay statement,Issue was escalated to the appropriate team,Europe,98,199.70,5,Yes
2,TKT0000003,CUST40644,AG0013,2025-12-19,2025-12-23,Critical,Recruitment,Job Posting,HCM,Resolved,Portal,Manager cannot complete the performance review,Issue was escalated to the appropriate team,Asia Pacific,308,167.65,5,Yes
3,TKT0000004,CUST28830,AG0536,2025-01-14,2025-01-21,Medium,Payroll,Tax,HCM,Closed,Portal,Employee is unable to update their profile,System behavior was verified and corrected,Asia Pacific,367,194.85,4,Yes
4,TKT0000005,CUST37408,AG0841,2025-04-19,2025-04-29,Low,Payroll,Direct Deposit,HCM,Open,Email,Direct deposit information is not updating,Knowledge article was provided,North America,57,139.32,3,Yes
5,TKT0000006,CUST35244,AG0955,2026-02-12,2026-02-21,Low,Core HR,Employment Status,HCM,Resolved,Email,Employee is unable to update their profile,Knowledge article was provided,Latin America,272,164.15,4,Yes
6,TKT0000007,CUST27908,AG0362,2026-04-06,2026-04-11,High,Core HR,Job Information,HCM,In Progress,Email,Direct deposit information is not updating,Issue was resolved after configuration update,North America,564,181.37,1,No
7,TKT0000008,CUST12080,AG0168,2026-08-19,2026-08-24,Medium,Core HR,Employee Profile,HCM,Open,Portal,Manager cannot complete the performance review,User permissions were corrected,Latin America,569,28.48,2,No
8,TKT0000009,CUST23825,AG0775,2026-01-12,2026-01-16,Medium,Recruitment,Job Posting,HCM,In Progress,Email,Direct deposit information is not updating,Knowledge article was provided,Latin America,200,133.20,4,Yes
9,TKT0000010,CUST46327,AG0239,2026-01-31,2026-02-02,Medium,Performance,Performance Review,HCM,Resolved,Phone,Employee is unable to request leave,Data was corrected in the system,Europe,178,121.96,3,Yes

Check the columns

In [18]:
test_df.columns

Index(['ticket_id', 'customer_id', 'agent_id', 'created_date', 'closed_date',
       'priority', 'category', 'sub_category', 'product', 'status', 'channel',
       'issue_description', 'resolution', 'customer_region',
       'first_response_minutes', 'resolution_hours', 'customer_satisfaction',
       'escalation_flag'],
      dtype='str')

Check the shape

In [19]:
print(
    "Rows:",
    test_df.shape[0]
)

print(
    "Columns:",
    test_df.shape[1]
)

Rows: 10
Columns: 18

Inspect the data

In [20]:
test_df.head(10)

,ticket_id,customer_id,agent_id,created_date,closed_date,priority,category,sub_category,product,status,channel,issue_description,resolution,customer_region,first_response_minutes,resolution_hours,customer_satisfaction,escalation_flag
0,TKT0000001,CUST05532,AG0389,2025-11-04,2025-11-12,Low,Payroll,Pay Statement,HCM,Open,Phone,Candidate information is not displaying correctly,Issue was resolved after configuration update,Europe,451,125.03,5,Yes
1,TKT0000002,CUST34709,AG0633,2025-08-19,2025-08-28,Medium,Benefits,Retirement,HCM,Open,Portal,Employee is unable to view their pay statement,Issue was escalated to the appropriate team,Europe,98,199.70,5,Yes
2,TKT0000003,CUST40644,AG0013,2025-12-19,2025-12-23,Critical,Recruitment,Job Posting,HCM,Resolved,Portal,Manager cannot complete the performance review,Issue was escalated to the appropriate team,Asia Pacific,308,167.65,5,Yes
3,TKT0000004,CUST28830,AG0536,2025-01-14,2025-01-21,Medium,Payroll,Tax,HCM,Closed,Portal,Employee is unable to update their profile,System behavior was verified and corrected,Asia Pacific,367,194.85,4,Yes
4,TKT0000005,CUST37408,AG0841,2025-04-19,2025-04-29,Low,Payroll,Direct Deposit,HCM,Open,Email,Direct deposit information is not updating,Knowledge article was provided,North America,57,139.32,3,Yes
5,TKT0000006,CUST35244,AG0955,2026-02-12,2026-02-21,Low,Core HR,Employment Status,HCM,Resolved,Email,Employee is unable to update their profile,Knowledge article was provided,Latin America,272,164.15,4,Yes
6,TKT0000007,CUST27908,AG0362,2026-04-06,2026-04-11,High,Core HR,Job Information,HCM,In Progress,Email,Direct deposit information is not updating,Issue was resolved after configuration update,North America,564,181.37,1,No
7,TKT0000008,CUST12080,AG0168,2026-08-19,2026-08-24,Medium,Core HR,Employee Profile,HCM,Open,Portal,Manager cannot complete the performance review,User permissions were corrected,Latin America,569,28.48,2,No
8,TKT0000009,CUST23825,AG0775,2026-01-12,2026-01-16,Medium,Recruitment,Job Posting,HCM,In Progress,Email,Direct deposit information is not updating,Knowledge article was provided,Latin America,200,133.20,4,Yes
9,TKT0000010,CUST46327,AG0239,2026-01-31,2026-02-02,Medium,Performance,Performance Review,HCM,Resolved,Phone,Employee is unable to request leave,Data was corrected in the system,Europe,178,121.96,3,Yes

Create the first dirty-data function — NULLs

In [21]:
def introduce_nulls(df):

    df = df.copy()

    null_columns = [
        "customer_id",
        "agent_id",
        "priority",
        "resolution",
        "customer_satisfaction"
    ]

    for column in null_columns:

        number_of_nulls = int(
            len(df) * 0.05
        )

        random_indexes = random.sample(
            range(len(df)),
            number_of_nulls
        )

        df.loc[
            random_indexes,
            column
        ] = None

    return df

Test the NULL function

In [22]:
records = []

for ticket_number in range(1, 101):

    ticket = generate_ticket(
        ticket_number
    )

    records.append(ticket)

test_df = pd.DataFrame(records)

dirty_test_df = introduce_nulls(
    test_df
)


dirty_test_df.isnull().sum()

ticket_id                 0
customer_id               5
agent_id                  5
created_date              0
closed_date               0
priority                  5
category                  0
sub_category              0
product                   0
status                    0
channel                   0
issue_description         0
resolution                5
customer_region           0
first_response_minutes    0
resolution_hours          0
customer_satisfaction     5
escalation_flag           0
dtype: int64

Create duplicate function

In [23]:
def introduce_duplicates(df):

    df = df.copy()

    duplicate_count = int(
        len(df) * 0.02
    )

    duplicate_rows = df.sample(
        n=duplicate_count,
        random_state=42
    )

    df = pd.concat(
        [
            df,
            duplicate_rows
        ],
        ignore_index=True
    )

    return df

Test duplicates

In [24]:
duplicate_test_df = introduce_duplicates(
    test_df
)

print(
    "Original rows:",
    len(test_df)
)

print(
    "Rows after duplicates:",
    len(duplicate_test_df)
)

Original rows: 100
Rows after duplicates: 102

Add More Dirty Data

Invalid Priority

In [25]:
def introduce_invalid_priority(df):

    df = df.copy()

    number_of_errors = int(
        len(df) * 0.02
    )

    random_indexes = random.sample(
        range(len(df)),
        number_of_errors
    )

    invalid_values = [
        "URGENT",
        "Super High",
        "Unknown Priority",
        "Very High"
    ]

    for index in random_indexes:

        df.loc[
            index,
            "priority"
        ] = random.choice(
            invalid_values
        )

    return df

In [26]:
invalid_priority_df = introduce_invalid_priority(
    test_df
)

valid_priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

invalid_priority_values = invalid_priority_df[
    ~invalid_priority_df["priority"].isin(
        valid_priorities
    )
]["priority"]

Inconsistent Priority Formatting

In [27]:
def introduce_inconsistent_priority(df):

    df = df.copy()

    number_of_errors = int(
        len(df) * 0.03
    )

    random_indexes = random.sample(
        range(len(df)),
        number_of_errors
    )

    inconsistent_values = [
        "high",
        "HIGH",
        " High",
        "high ",
        "critical",
        "CRITICAL",
        " low",
        "medium "
    ]

    for index in random_indexes:

        df.loc[
            index,
            "priority"
        ] = random.choice(
            inconsistent_values
        )

    return df

In [28]:
inconsistent_priority_df = introduce_inconsistent_priority(
    test_df
)

print(
    inconsistent_priority_df["priority"].value_counts()
)

priority
Low         31
Critical    26
Medium      22
High        18
CRITICAL     2
 low         1
Name: count, dtype: int64

Invalid Customer Satisfaction

In [29]:
def introduce_invalid_csat(df):

    df = df.copy()

    number_of_errors = int(
        len(df) * 0.02
    )

    random_indexes = random.sample(
        range(len(df)),
        number_of_errors
    )

    invalid_values = [
        0,
        6,
        7,
        10,
        -1
    ]

    for index in random_indexes:

        df.loc[
            index,
            "customer_satisfaction"
        ] = random.choice(
            invalid_values
        )

    return df

In [31]:
invalid_csat_df = introduce_invalid_csat(
    test_df
)

print(
    invalid_csat_df[
        (invalid_csat_df["customer_satisfaction"] < 1) |
        (invalid_csat_df["customer_satisfaction"] > 5)
    ][
        "customer_satisfaction"
    ]
)

7     10
23     7
Name: customer_satisfaction, dtype: int64

Invalid Dates

In [39]:
def introduce_invalid_dates(df):

    df = df.copy()

    # Allow both dates and invalid strings
    df["created_date"] = df["created_date"].astype(object)

    number_of_errors = int(
        len(df) * 0.01
    )

    random_indexes = random.sample(
        range(len(df)),
        number_of_errors
    )

    invalid_dates = [
        "2026-02-30",
        "2026-02-31",
        "2026-13-01",
        "not_a_date",
        "2025-99-99"
    ]

    for index in random_indexes:

        df.loc[
            index,
            "created_date"
        ] = random.choice(
            invalid_dates
        )

    return df

In [40]:
invalid_dates_df = introduce_invalid_dates(
    test_df
)

In [41]:
print(
    invalid_csat_df[
        (invalid_csat_df["customer_satisfaction"] < 1) |
        (invalid_csat_df["customer_satisfaction"] > 5)
    ][
        "customer_satisfaction"
    ]
)

7     10
23     7
Name: customer_satisfaction, dtype: int64

Invalid Dates

In [45]:
def introduce_invalid_dates(df):

    df = df.copy()

    # Convert dates to strings
    df["created_date"] = df["created_date"].astype(str)

    number_of_errors = int(
        len(df) * 0.01
    )

    random_indexes = random.sample(
        range(len(df)),
        number_of_errors
    )

    invalid_dates = [
        "2026-02-30",
        "2026-02-31",
        "2026-13-01",
        "not_a_date",
        "2025-99-99"
    ]

    for index in random_indexes:

        df.loc[
            index,
            "created_date"
        ] = random.choice(
            invalid_dates
        )

    return df

In [46]:
invalid_dates_df = introduce_invalid_dates(
    test_df
)

print(
    invalid_dates_df[
        "created_date"
    ].head(20)
)

0     2026-01-04
1     2026-05-04
2     2025-11-26
3     2025-06-25
4     2025-08-16
5     2026-05-09
6     2025-03-12
7     2025-08-05
8     2025-07-30
9     2025-12-26
10    2026-06-30
11    2025-01-21
12    2026-06-23
13    2025-08-12
14    2025-01-03
15    2025-04-13
16    2025-10-09
17    2026-05-16
18    2026-05-23
19    2025-08-08
Name: created_date, dtype: str

Extreme Resolution Hours

In [47]:
def introduce_outliers(df):

    df = df.copy()

    number_of_outliers = int(
        len(df) * 0.01
    )

    random_indexes = random.sample(
        range(len(df)),
        number_of_outliers
    )

    for index in random_indexes:

        df.loc[
            index,
            "resolution_hours"
        ] = random.uniform(
            5000,
            50000
        )

    return df

In [48]:
outlier_df = introduce_outliers(
    test_df
)

In [49]:
print(
    outlier_df[
        outlier_df["resolution_hours"] > 500
    ][
        [
            "ticket_id",
            "resolution_hours"
        ]
    ]
)

     ticket_id  resolution_hours
70  TKT0000071      33005.745234

Combine All Dirty-Data Functions

In [50]:
def create_dirty_dataset(df):

    df = introduce_nulls(df)

    df = introduce_duplicates(df)

    df = introduce_invalid_priority(df)

    df = introduce_inconsistent_priority(df)

    df = introduce_invalid_csat(df)

    df = introduce_invalid_dates(df)

    df = introduce_outliers(df)

    return df

Test the Complete Dirty Dataset

In [51]:
dirty_test_df = create_dirty_dataset(
    test_df
)

In [52]:
print(
    "Original rows:",
    len(test_df)
)

print(
    "Dirty rows:",
    len(dirty_test_df)
)

Original rows: 100
Dirty rows: 102

Generate the Real 1.2 Million Dataset

In [53]:
TOTAL_RECORDS = 1_200_000

CHUNK_SIZE = 50_000

Prepare the Output File

In [54]:
import os

raw_path = "../data/raw/support_tickets_raw.csv"

os.makedirs(
    "../data/raw",
    exist_ok=True
)

if os.path.exists(raw_path):

    os.remove(raw_path)

print(
    "Ready to generate:",
    raw_path
)

Ready to generate: ../data/raw/support_tickets_raw.csv

Generate the Dataset

In [55]:
first_chunk = True

for start in range(
    1,
    TOTAL_RECORDS + 1,
    CHUNK_SIZE
):

    end = min(
        start + CHUNK_SIZE,
        TOTAL_RECORDS + 1
    )

    records = []

    for ticket_number in range(
        start,
        end
    ):

        ticket = generate_ticket(
            ticket_number
        )

        records.append(ticket)

    chunk_df = pd.DataFrame(
        records
    )

    chunk_df = create_dirty_dataset(
        chunk_df
    )

    chunk_df.to_csv(
        raw_path,
        mode="w" if first_chunk else "a",
        header=first_chunk,
        index=False
    )

    first_chunk = False

    print(
        f"Generated records: "
        f"{start:,} - {end - 1:,}"
    )

Generated records: 1 - 50,000
Generated records: 50,001 - 100,000
Generated records: 100,001 - 150,000
Generated records: 150,001 - 200,000
Generated records: 200,001 - 250,000
Generated records: 250,001 - 300,000
Generated records: 300,001 - 350,000
Generated records: 350,001 - 400,000
Generated records: 400,001 - 450,000
Generated records: 450,001 - 500,000
Generated records: 500,001 - 550,000
Generated records: 550,001 - 600,000
Generated records: 600,001 - 650,000
Generated records: 650,001 - 700,000
Generated records: 700,001 - 750,000
Generated records: 750,001 - 800,000
Generated records: 800,001 - 850,000
Generated records: 850,001 - 900,000
Generated records: 900,001 - 950,000
Generated records: 950,001 - 1,000,000
Generated records: 1,000,001 - 1,050,000
Generated records: 1,050,001 - 1,100,000
Generated records: 1,100,001 - 1,150,000
Generated records: 1,150,001 - 1,200,000

Load Raw Data Using PySpark